[package]
name = "pop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.42"
futures = "0.3.1"
async-std = { version = "1.6.2", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
cid = { version = "0.6", default-features = false, features = ["std"] }
libipld  = "0.12"
async-recursion = "0.3.1"
async-trait = "0.1"
thiserror = "1.0"
serde_cbor = { package = "cs_serde_cbor", version = "0.12", features = [
    "tags"
] }
hex = "0.4.3"
fnv = "1.0.6"
protobuf = "2.25.2"
unsigned-varint = { version = "0.7.1", features = ["futures"] }
integer-encoding = { version = "3.0", default-features = false }
bytes = "1.0"

[build-dependencies]
protoc-rust = "2.25.2"

[dev-dependencies]
serde_json = "1.0"
